export const CREATE_SURVEY_REQUEST = "CREATE_SURVEY_REQUEST";
export const CREATE_SURVEY_SUCCESS = "CREATE_SURVEY_SUCCESS";
export const CREATE_SURVEY_FAIL = "CREATE_SURVEY_FAIL";
export const CREATE_SURVEY_RESET = "CREATE_SURVEY_RESET";
export const RESET_FORM = "RESET_FORM";
